INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Shining','Stephen','King','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Simetierre','Stephen','King','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 1','Stephen','King','17','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Cujo','Stephen','King','2','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Aliss','Patrick','Senécal','0','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Désolation','Stephen','King','3','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Cellulaire','Stephen','King','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Dreamcatcher','Stephen','King','6','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Une fille comme les autres','Jack','Ketchum','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le secret de Crickley Hall','James','Herbert','8','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 2','Stephen','King','17','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 3','Stephen','King','16','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Horrorstör','Grady','Hendrix','0','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Conception','Scott','Spencer','24','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Sur le seuil','Patrick','Senécal','0','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('L''exorciste','William','Blatty','3','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le passager','Patrick','Senécal','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('5150, rue des Ormes','Patrick','Senécal','1','1');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('1984','George','Orwell','7','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Hunger Games, tome 1','Suzanne','Collins','15','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le meilleur des Mondes','Aldous','Huxley','5','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('La nuit des temps','René','Barjavel','7','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Fahrenheit 451','Ray','Bradbury','3','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Des fleurs pour Algernon','Daniel','Keyes','4','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('La Horde du Contrevent','Alain','Damasio','5','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('La guerre des mondes','H.G.','Wells','6','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Les Fourmis','Bernard','Werber','7','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ravage','René','Barjavel','8','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Terrienne','Jean-Claude','Mourlevat','9','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Je suis une légende','Richard','Matheson','10','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Phobos, tome 1 : Les éphémères','Victor','Dixen','11','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le passeur','Lois','Lowry','12','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('L''affaire Jane Eyre','Jasper','Fforde','13','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Chroniques martiennes','Ray','Bradbury','14','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('La Planète des singes','Pierre','Boulle','15','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le cycle de Dune, tome 1 : Dune','Frank','Herbert','16','2');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Shining','Stephen','King','7','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Chroniques martiennes','Ray','Bradbury','14','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('5150, rue des Ormes','Patrick','Senécal','1','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Dreamcatcher','Stephen','King','6','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Horrorstör','Grady','Hendrix','0','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Cellulaire','Stephen','King','1','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('L''affaire Jane Eyre','Jasper','Fforde','13','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Fahrenheit 451','Ray','Bradbury','3','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le cycle de Dune, tome 1 : Dune','Frank','Herbert','16','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Cujo','Stephen','King','2','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Les Fourmis','Bernard','Werber','7','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Des fleurs pour Algernon','Daniel','Keyes','4','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 1','Stephen','King','17','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 2','Stephen','King','17','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Ça, tome 3','Stephen','King','16','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('1984','George','Orwell','7','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Terrienne','Jean-Claude','Mourlevat','9','3');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le combat d''hiver','Jean-Claude','Mourlevat','12','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Tobie Lolness, Tome 1 : La vie suspendue','Timothée','De Fombelle','9','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le Livre de Perle','Timothée','De Fombelle','9','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Oh, boy !','Marie-Aude','Murail','2','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Peter Pan','J. M.','Barrie','24','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('35 kilos d''espoir','Anna','Gavalda','25','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Les malheurs de Sophie','Comtesse','De Ségur','3','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('La Bibliothécaire','Gudule','Gudule','15','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Les filles au chocolat, Tome 2 : Coeur guimauve','Cathy','Cassidy','1','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le royaume de Kensuké','Michael','Morpurgo','0','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Big easy','Ruta','Sepetys','2','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Une bouteille dans la mer de Gaza','Valérie','Zenatti','11','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le temps des miracles','Anne-Laure','Bondoux','4','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('De Cape et de mots','Flore','Vesco','6','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Tobie Lolness, tome 2 : Les yeux d''Elisha','Timothée','De Fombelle','1','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le Magicien d''Oz','Lyman Frank','Baum','22','4');
INSERT INTO `Livres`(`Titre`,`NAuteur`,`PAuteur`,`Popularite`,`id_Genres`)VALUES('Le chagrin du roi mort','Jean-Claude','Mourlevat','1','4');